### PR TITLE
Updated podfile and bumped podspec ios version to 8.0

### PR DESCRIPTION
**Pull request by kevnm67**
I updated the podfile to work with the latest cocoapods version and bumped the podspec ios version to 8.0.  I ran unit tests locally, which are all passing.

### CODE REVIEW

**Comment by belkevich** [comment]
Hi Kevin,

Sorry for delay. Everything looks good. 
But why you decided to bump ios version?

**Comment by kevnm67** [comment]
No worries.  Sorry for my late response.

The reason for bumping the base SDK was mainly because the percentage of users, as of 1/2017, on iOS < 8 was %6.  I'm happy to change it to whatever base SDK you want though ;)

**Comment by belkevich** [comment]
I think it's better to leave ios5. May be someone will need it?

**Comment by kevnm67** [comment]
sounds good. Ill make the change.

**Pull request merged**
