### PR TITLE
Fixed deprecations

### PR DESCRIPTION
**Pull request by kevnm67**
Fixed the deprecations.

### CODE REVIEW

**Comment by belkevich** [comment]
Hello!
Thank you for pull request. But it breaks two unit-tests. It's ok, I'll fix it.
Next time run tests before sending pull request =)

**Comment by kevnm67** [comment]
sorry about that. I'll be sure to run tests next time ;)

**Comment by belkevich** [comment]
It's ok. New release version is 0.0.7. Update your podfile!

**Comment by kevnm67** [comment]
Great! Thanks for fixing and merging the changes. I appreciate the categories.

**Pull request merged**
